import {useMemo,useState} from 'react'; import {Activity,Pause,Play,RotateCcw,ChevronDown,Eye,EyeOff} from 'lucide-react'; import ECGMonitor from './ECGMonitor'; import {RHYTHMS,rhythmById} from './rhythms'; import type {RhythmId,SimParams} from './types';
const cats=[...new Set(RHYTHMS.map(r=>r.category))];
export default function App(){
 const [id,setId]=useState<RhythmId>('sinus'); const rhythm=rhythmById(id);
 const [p,setP]=useState<SimParams>({rate:75,amplitude:1,paperSpeed:25,gain:10,paused:false,running:true,challenge:false,avConduction:2});
 const [score,setScore]=useState({ok:0,bad:0,streak:0}); const [answer,setAnswer]=useState<RhythmId|null>(null); const [revealed,setRevealed]=useState(false);
 const choose=(next:RhythmId)=>{const r=rhythmById(next);setId(next);setP(x=>({...x,rate:r.defaultRate,amplitude:r.defaultAmplitude,paused:false,running:true}));setAnswer(null);setRevealed(false)};
 const pct=score.ok+score.bad?Math.round(score.ok/(score.ok+score.bad)*100):0;
 const challengeOptions=useMemo(()=>RHYTHMS.slice(0,8).sort(()=>Math.random()-.5).slice(0,4),[id,p.challenge]);
 const submit=(x:RhythmId)=>{if(answer)return;const ok=x===id;setAnswer(x);setScore(s=>({ok:s.ok+(ok?1:0),bad:s.bad+(ok?0:1),streak:ok?s.streak+1:0}));};
 return <main className="app"><header><div className="brand"><Activity size={18}/><span>ECG RHYTHM SIMULATOR</span></div><div className="status"><i/> MONITORING <b>DERIVAÇÃO II</b></div></header>
 <section className="workspace"><div className="monitor-wrap"><div className="monitor-top"><div><strong>{p.challenge&&!revealed?'RITMO OCULTO':rhythm.name.toUpperCase()}</strong><small>{p.rate} BPM · {p.paperSpeed} MM/S · {p.gain} MM/MV</small></div><div className="mode"><button className={!p.challenge?'active':''} onClick={()=>setP(x=>({...x,challenge:false}))}>SIMULAÇÃO</button><button className={p.challenge?'active':''} onClick={()=>{setP(x=>({...x,challenge:true}));setAnswer(null);setRevealed(false)}}>DESAFIO</button></div></div><ECGMonitor rhythm={rhythm} params={p}/><div className="monitor-footer"><span>AMPLITUDE <b>{p.amplitude.toFixed(1)}×</b></span><span>STATUS <b>{p.paused?'PAUSADO':'ATIVO'}</b></span><span>BASELINE <b>STABLE</b></span></div></div>
 <aside className="control"><div className="control-head"><span>RHYTHM LIBRARY</span><span className="live">LIVE</span></div><div className="rhythms">{cats.map(c=><div className="group" key={c}><div className="cat">{c}</div>{RHYTHMS.filter(r=>r.category===c).map(r=><button key={r.id} className={id===r.id?'selected':''} onClick={()=>choose(r.id)}>{r.name}<span/></button>)}</div>)}</div>
 <div className="parameters"><div className="section-title">PARÂMETROS</div><label>FREQUÊNCIA <b>{p.rate} BPM</b><input type="range" min={rhythm.rateRange[0]} max={rhythm.rateRange[1]} value={p.rate} onChange={e=>setP(x=>({...x,rate:+e.target.value}))}/></label><label>AMPLITUDE <b>{p.amplitude.toFixed(1)}×</b><input type="range" min=".3" max="2" step=".1" value={p.amplitude} onChange={e=>setP(x=>({...x,amplitude:+e.target.value}))}/></label><div className="seg"><span>VELOCIDADE</span><button className={p.paperSpeed===25?'on':''} onClick={()=>setP(x=>({...x,paperSpeed:25}))}>25</button><button className={p.paperSpeed===50?'on':''} onClick={()=>setP(x=>({...x,paperSpeed:50}))}>50</button></div><div className="seg"><span>GANHO</span><button className={p.gain===5?'on':''} onClick={()=>setP(x=>({...x,gain:5}))}>5</button><button className={p.gain===10?'on':''} onClick={()=>setP(x=>({...x,gain:10}))}>10</button><button className={p.gain===20?'on':''} onClick={()=>setP(x=>({...x,gain:20}))}>20</button></div>{(id==='flutter'||id==='av-block-complete')&&<div className="seg"><span>CONDUÇÃO AV</span><button className={p.avConduction===2?'on':''} onClick={()=>setP(x=>({...x,avConduction:2}))}>2:1</button><button className={p.avConduction===3?'on':''} onClick={()=>setP(x=>({...x,avConduction:3}))}>3:1</button><button className={p.avConduction===4?'on':''} onClick={()=>setP(x=>({...x,avConduction:4}))}>4:1</button></div>}</div>
 <div className="transport"><button onClick={()=>setP(x=>({...x,running:true,paused:false}))}><Play size={15}/></button><button onClick={()=>setP(x=>({...x,paused:!x.paused}))}><Pause size={15}/></button><button onClick={()=>setP(x=>({...x,paused:false,running:true}))}><RotateCcw size={15}/></button></div></aside></section>
 {p.challenge&&<section className="challenge"><div><div className="challenge-label">IDENTIFIQUE O RITMO</div><strong>{answer?answer===id?'CORRETO':'INCORRETO':'QUAL É O RITMO?'}</strong></div><div className="answers">{challengeOptions.map(r=><button key={r.id} disabled={!!answer} className={answer&&r.id===id?'correct':''} onClick={()=>submit(r.id)}>{r.name}</button>)}<button className="reveal" onClick={()=>setRevealed(v=>!v)}>{revealed?<EyeOff size={15}/>:<Eye size={15}/>} {revealed?'OCULTAR':'REVELAR'}</button></div><div className="score"><span>ACERTOS <b>{score.ok}</b></span><span>ERROS <b>{score.bad}</b></span><span>PRECISÃO <b>{pct}%</b></span><span>STREAK <b>{score.streak}</b></span></div></section>}
 {p.challenge&&revealed&&<section className="reveal-panel"><b>{rhythm.name}</b><span>{p.rate} BPM · {rhythm.regularity} · QRS {rhythm.qrsWidth<.12?'estreito':'largo'}</span></section>}
 </main>
}